apiVersion: v1
kind: ReplicationController
metadata:
  name: seed-angular-rc
spec:
  replicas: 5
  selector:
    app: seed-angular
  template:
    metadata:
      labels:
        app: seed-angular
    spec:
      containers:
      - name: seed-angular-ctr
        image: systelab/seed-angular:latest
        ports:
        - containerPort: 80